//
// Created by DELL on 14-06-2024.
//

#ifndef RUBICKSCUBESOLVER_GENERICRUBIKSCUBE_H
#define RUBICKSCUBESOLVER_GENERICRUBIKSCUBE_H


class GenericRubiksCube {

};


#endif //RUBICKSCUBESOLVER_GENERICRUBIKSCUBE_H
